server:
  port: 8081
  code: 1000

spring:
    datasource:
      druid:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/imooc_new?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: a123321520

mybatis-plus:
  configuration:
    # 开启sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com.baomidou.mybatisplus.extension.plugins.pagination.Page: DEBUG
    org.mybatis.spring: DEBUG


